# Generated by Django 5.2.1 on 2025-05-16 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Topshiriq nomi')),
                ('description', models.TextField(blank=True, verbose_name='Topshiriq tavsifi')),
                ('audio', models.FileField(blank=True, null=True, upload_to='assignments/audio/', verbose_name='Audio')),
                ('video', models.FileField(blank=True, null=True, upload_to='assignments/video/', verbose_name='Video')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assignments/images/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsifi')),
                ('image', models.ImageField(upload_to='courses/images/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='CompletedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to='exercises.assignment')),
            ],
            options={
                'verbose_name': 'Bajarilgan topshiriq',
                'verbose_name_plural': 'Bajarilgan topshiriqlar',
            },
        ),
    ]
