# Generated by Django 5.2.1 on 2025-05-22 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['course', 'order'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задании'},
        ),
        migrations.AlterModelOptions(
            name='completedassignment',
            options={'verbose_name': 'Выполненное задание', 'verbose_name_plural': 'Выполненные задании'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='Ученики', related_query_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='assignments/audio/', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exercises.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assignments/images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер последовательности'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='assignments/video/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='completedassignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_assignments', to='exercises.assignment'),
        ),
        migrations.AlterField(
            model_name='completedassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано в'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses/images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
